### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "test123",
  "email": "test@gmail.com",
  "password": "12345!Bar"
}

###

### Register a new user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "test123",
  "password": "12345!Bar"
}

###

### Register a new post
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhMjVmZjYzNC1jNDhlLTQ4YzktOGYxNS1mMTljZDFjMjY4ODQiLCJ1c2VybmFtZSI6InRlc3QxMjMiLCJleHAiOjE3Njk3MDUzNjZ9.dyptrjgDtEyNjJTjdQpLryk-EnM8oVBab_-efa5sPp0

###

