### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "test123",
  "email": "test@gmail.com",
  "password": "12345!Bar"
}

###

### Register a new user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "test123",
  "password": "12345!Bar"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

###

### Create a new post
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Hello world",
  "content": "content"
}

> {%
    client.global.set("post_id", response.body.id);
%}

###

### Update post
PUT http://localhost:3000/api/posts/{{post_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Hello",
  "content": "Updated content"
}

###

